const AsteroidImg = require('../assets/asteroid.png')
const BronzecoinImg = require('../assets/bronzecoin.png')
const FuelImg = require('../assets/fuel.png')
const GoldcoinImg = require('../assets/goldcoin.png')
const RocketImg = require('../assets/rocket.png')
const SilvercoinImg = require('../assets/silvercoin.png')
const SpaceImg = require('../assets/space.jpg')
const FireImg = require('../assets/fire.png')
const ArrowImg = require('../assets/arrow.png')
const CoinImg = require('../assets/coin.png')
const Boost = require('../assets/boost.png')
const Friend = require('../assets/friend.png')
const Missions = require('../assets/missions.png')
const Result = require('../assets/result.png')
const Oil = require('../assets/oil.png')
const Oil_em = require('../assets/oil_em.png')
const Friendship = require('../assets/friendship.png')
const OilBoost = require('../assets/oil_boost.png')
const Forward = require('../assets/forward.png')
const Shield = require('../assets/shield.png')
const GasPump = require('../assets/gas-pump.png')


export{ AsteroidImg, BronzecoinImg, FuelImg, GoldcoinImg, RocketImg, SilvercoinImg, SpaceImg, ArrowImg, CoinImg, FireImg, Result, Missions, Friend, Boost, Oil, Oil_em, Friendship, OilBoost, Forward, Shield, GasPump }